---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: ${{ values.name }}-sqlserver
  namespace: ws-${{ values.workspaceKey }}
spec:
  application: ${{ values.name }}
  container:
    containers:
      - env:
          - name: MSSQL_SA_PASSWORD
            value: Password123
          - name: ACCEPT_EULA
            value: Y
        image: mcr.microsoft.com/mssql/server:2022-latest
        name: sqlserver
        ports:
          - containerPort: 1433
            expose: true
            name: sqlserver
            protocol: TCP
    replicas: 1
    tls: true
  key: sqlserver
  name: sqlserver
  type: Container
---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: ${{ values.name }}-app
  namespace: ws-${{ values.workspaceKey }}
spec:
  application: ${{ values.name }}
  container:
    containers:
      - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: MSSQL_HOSTNAME
            value: sqlserver
          - name: MSSQL_PORT
            value: 1433
          - name: MSSQL_DBNAME
            value: MainDemo
          - name: MSSQL_USERNAME
            value: sa
          - name: MSSQL_PASSWORD
            value: Password123
        image: ghcr.io/appvia/aspnet-app:latest
        name: app
        ports:
          - containerPort: 8080
            expose: true
            name: http
            protocol: TCP
    expose:
      container: app
      port: 8080
    replicas: 1
    tls: true
  dependsOn:
    - sqlserver
  key: app
  name: app
  type: Container
